FROM envoyproxy/envoy:v1.19.1

# Install dependencies for the script to add data into db(e.g., Python, pip, PyYAML)
RUN apt-get update && apt-get install -y python3 python3-pip && pip3 install PyYAML

