# 选择 Python3.9 作为基础镜像
FROM python:3.9

# 设置工作目录
WORKDIR /app

# 复制 requirements.txt 并安装依赖
COPY mspj/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# 复制 Flask 代码
COPY mspj /app

# 运行 Flask 应用
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
