{
 "title": "HelloWorld",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "http_downstream_rq_http2_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "imo_http_downstream_rq_http2_total",
     "legendFormat": "{{envoy}}"
    }
   ]
  },
  {
   "title": "http_downstream_cx_rx_bytes from listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_http_downstream_cx_rx_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "service": "envoy_client" },
    {}
   ]
  },
  {
   "title": "http_downstream_cx_tx_bytes from listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_http_downstream_cx_tx_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stats Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"otlp_stats\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.metrics"
    },
    {
     "expr": "rate(imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"jaeger_stats\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.trace"
    }
   ]
  },
  {
   "title": "xds controller bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"xds_cluster\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.tx"
    },
    {
     "expr": "rate(imo_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=\"xds_cluster\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.rx"
    }
   ]
  }
 ]
}