global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'envoy_client'
    metrics_path: "/stats/prometheus"
    scrape_interval: 2s
    static_configs:
      - targets: ['172.18.0.12:9901']

  - job_name: 'otlp_imo'
    static_configs:
      - targets: ['otelcol:8888']
      - targets: ['otelcol:8889']
